spring.application.name=trivia

spring.datasource.url=jdbc:sqlite:./questions.sqlite

# Hibernate settings
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update